version: '2'
services:
  api:
    build: .
    environment:
      NODE_ENV: "development"
    command: puma config.ru
    volumes:
    - .:/usr/todo
    links:
    - db
    - rmq
  db:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - /data/db2/:/data/db/
    command: /usr/bin/mongod --smallfiles
